name: Platforms compatibility check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Pure.Primitives.Date.Operations

    strategy:
      fail-fast: false
      matrix:
        dotnet: [ '7.0', '8.0', '9.0', '10.0' ]

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET SDK ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build NativeAOT linux-x64 with .NET ${{ matrix.dotnet }}
        run: dotnet publish --framework net${{ matrix.dotnet }} --runtime linux-x64 --self-contained --configuration Release -warnaserror

      - name: Build NativeAOT linux-arm64 with .NET ${{ matrix.dotnet }}
        run: dotnet publish --framework net${{ matrix.dotnet }} --runtime linux-arm64 --self-contained --configuration Release -warnaserror

      - name: Build NativeAOT linux-arm with .NET ${{ matrix.dotnet }}
        run: dotnet publish --framework net${{ matrix.dotnet }} --runtime linux-arm --self-contained --configuration Release -warnaserror

      - name: Build NativeAOT win-x64 with .NET ${{ matrix.dotnet }}
        run: dotnet publish --framework net${{ matrix.dotnet }} --runtime win-x64 --self-contained --configuration Release -warnaserror

      - name: Build NativeAOT win-arm64 with .NET ${{ matrix.dotnet }}
        run: dotnet publish --framework net${{ matrix.dotnet }} --runtime win-arm64 --self-contained --configuration Release -warnaserror

      - name: Build NativeAOT win-x86 with .NET ${{ matrix.dotnet }}
        run: dotnet publish --framework net${{ matrix.dotnet }} --runtime win-x86 --self-contained --configuration Release -warnaserror

      - name: Build NativeAOT osx-x64 with .NET ${{ matrix.dotnet }}
        run: dotnet publish --framework net${{ matrix.dotnet }} --runtime osx-x64 --self-contained --configuration Release -warnaserror

      - name: Build NativeAOT osx-arm64 with .NET ${{ matrix.dotnet }}
        run: dotnet publish --framework net${{ matrix.dotnet }} --runtime osx-arm64 --self-contained --configuration Release -warnaserror
